#!/bin/bash

ARGUMENT_COMPARISON_AHEAD=AHEAD
ARGUMENT_COMPARISON_IDENTICAL=IDENTICAL
ARGUMENT_COMPARISON_BEHIND=BEHIND

ARGUMENT_STEP_BEFORE_COMPOSER=BEFORE_COMPOSER
ARGUMENT_STEP_BEFORE_MAGENTO_COMMANDS=BEFORE_MAGENTO_COMMANDS
ARGUMENT_STEP_BEFORE_COMMON_TOOLS=BEFORE_COMMON_TOOLS
ARGUMENT_STEP_FINAL=FINAL

INPUT="$1-$2"

case $INPUT in
        "$ARGUMENT_STEP_BEFORE_COMPOSER-$ARGUMENT_COMPARISON_AHEAD")
            set -xe
            # do something
            ;;
        "$ARGUMENT_STEP_BEFORE_COMPOSER-$ARGUMENT_COMPARISON_IDENTICAL")
            set -xe
            # do something. set to exec
            ;;
        "$ARGUMENT_STEP_BEFORE_COMPOSER-$ARGUMENT_COMPARISON_BEHIND")
            set -xe
            # do something
            ;;
        "$ARGUMENT_STEP_BEFORE_MAGENTO_COMMANDS-$ARGUMENT_COMPARISON_AHEAD")
            set -xe
            ~/htdocs/mdoq/migrate.sh

            ;;
        "$ARGUMENT_STEP_BEFORE_MAGENTO_COMMANDS-$ARGUMENT_COMPARISON_IDENTICAL")
            set -xe
            # do something
            ;;
        "$ARGUMENT_STEP_BEFORE_MAGENTO_COMMANDS-$ARGUMENT_COMPARISON_BEHIND")
            set -xe
            # do something
            ;;
        "$ARGUMENT_STEP_BEFORE_COMMON_TOOLS-$ARGUMENT_COMPARISON_AHEAD")
            set -xe
            # do something
            ;;
        "$ARGUMENT_STEP_BEFORE_COMMON_TOOLS-$ARGUMENT_COMPARISON_IDENTICAL")
            set -xe
            # do something
            ;;
        "$ARGUMENT_STEP_BEFORE_COMMON_TOOLS-$ARGUMENT_COMPARISON_BEHIND")
            set -xe
            # do something
            ;;
        "$ARGUMENT_STEP_FINAL-$ARGUMENT_COMPARISON_AHEAD")
            set -xe
            ;;
        "$ARGUMENT_STEP_FINAL-$ARGUMENT_COMPARISON_IDENTICAL")
            set -xe
            # do something
            ;;
        "$ARGUMENT_STEP_FINAL-$ARGUMENT_COMPARISON_BEHIND")
            set -xe
            # do something
            ;;
        "$ARGUMENT_STEP_FINAL-*")
            set -xe
            bin/magento setup:upgrade;
            bin/magento cache:enable;
            bin/magento indexer:reindex;      
            ;;
        *)
            echo "input not recognized: $INPUT"
            exit 1
esac
